name: test
on:
  push:
  workflow_dispatch:

jobs:
  main:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - run: make v2_pactjs_v9_consumer_install
      - run: make v2_pactjs_v9_consumer_test
      - run: make v2_pactjs_v9_provider_install
      - run: make v2_pactjs_v9_provider_test_local
      - run: make v3_pactjs_v10_consumer_install
      - run: make v3_pactjs_v10_consumer_test
      - run: make v3_pactjs_v10_provider_install
      - run: make v3_pactjs_v10_provider_test_local