name: test
on:
  push:
  workflow_dispatch:

jobs:
  main:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x,  16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - run: make v2_pactjs_v9_consumer_install
      - run: make v2_pactjs_v9_consumer_test
      - run: make v2_pactjs_v9_provider_install
      - run: make v2_pactjs_v9_provider_test_local
      # - run: make v2_pactjs_v10_consumer_install
      # - run: make v2_pactjs_v10_consumer_test
      # - run: make v2_pactjs_v10_provider_install
      # - run: make v2_pactjs_v10_provider_test_local
      # - run: make v3_pactjs_v10_consumer_install
      # - run: make v3_pactjs_v10_consumer_test
      # - run: make v3_pactjs_v10_provider_install
      # - run: make v3_pactjs_v10_provider_test_local