name: test
on:
  push:
  workflow_dispatch:

jobs:
  main:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        spec: [v2, v3, v4]
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: make ${{ matrix.spec }}_consumer_install
      - run: make ${{ matrix.spec }}_consumer_test
      - run: make ${{ matrix.spec }}_provider_install
      - run: make ${{ matrix.spec }}_provider_test_local