name: test2
on:
  push:
  workflow_dispatch:

jobs:
  main:
    name: Build & Test
    # needs: prepare-config
    runs-on: ubuntu-latest
    services:
      verdaccio:
        image: verdaccio/verdaccio:latest
        ports:
          - 4873:4873
    strategy:
      matrix:
        node-version: [24.x]
        # spec: [v2]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Verdaccio
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4873/; then
              echo "Verdaccio is up!"
              break
            fi
            echo "Waiting for Verdaccio..."
            sleep 2
          done

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'http://localhost:4873'

      - name: Login to Verdaccio
        run: |
          npm install -g @kenan/npm-cli-login
          NPM_REGISTRY=http://localhost:4873 NPM_USER=test NPM_PASS=test NPM_EMAIL=test@example.com npm-cli-login
          # npm-cli-login -u test -p test -e test@example.com -r http://localhost:4873

      # - run: |
      #     git config --global user.email "you@example.com"
      #     git config --global user.name "Your Name"

      - run: |
          cd v2_spec/consumer
          npm publish

      - name: Clone and Build Pact.js
        run: |
          cd /tmp
          git clone https://github.com/pact-foundation/pact-js
          cd pact-js
          git checkout feat/v4-asynchronous-messages-pact-core-v17
          npm install
          npm run release
          npm run dist
          npm publish ./dist --access public --tag latest

      - name: Clone and Build Nest.js Pact
        run: |
          cd /tmp
          git clone https://github.com/pact-foundation/nestjs-pact
          cd nestjs-pact
          git checkout feat/v3_v4_interface
          yarn add @pact-foundation/pact@^16.0.0 --save-dev
          yarn install
          yarn build
          npm publish

      # - run: make ${{ matrix.spec }}_consumer_install
      # - run: make ${{ matrix.spec }}_consumer_test
      # - run: make ${{ matrix.spec }}_provider_install
      # - run: make ${{ matrix.spec }}_provider_test_local
      - run: make v2_consumer_install
      - run: make v2_consumer_test
      - run: make v2_provider_install
      - run: make v2_provider_test_local
      - run: make v3_consumer_install
      - run: make v3_consumer_test
      - run: make v3_provider_install
      - run: make v3_provider_test_local
      - run: make v4_consumer_install
      - run: make v4_consumer_test
      - run: make v4_provider_install
      - run: make v4_provider_test_local
